const { elemAleatorio, getRandomInt } = require('./arlutils.js');
exports.RESPUESTA = 1;
exports.COMENTARIO = 2;

exports.SALUDOS = [
    'Hola',
    'Ola',
    'Hola buen día',
    'Holi',
    'oli',
    '<:ola:957609803109269544>',
    'ola',
    'Hola',
    'Buen día',
    'Hola buenas',
    'HOLA',
    'Saludos',
    'Hola :)',
    'Hola que tal',
    'Holas',
    'Oli',
    'Ola',
    '<:bob_feliz:947374616836448267>',
    'Hola equipo',
    'Buenos días',
    'olas',
    'Bvuenos días'
];

FRASES = [
    ['¿Que pasó?', exports.COMENTARIO],
    ['¿Tu otra ves?', exports.COMENTARIO],
    ['Concuerdo con {0}', exports.COMENTARIO],
    ['xd', exports.COMENTARIO],
    ['<:quienpingeo:958452373385261076>', exports.COMENTARIO],
    ['<:juanita:945499915113619486>', exports.COMENTARIO],
    ['<:bob_feliz:947374616836448267>', exports.COMENTARIO | exports.RESPUESTA],
    ['Hola', exports.COMENTARIO],
    ['?', exports.COMENTARIO | exports.RESPUESTA],
    ['Hola que tal :)', exports.COMENTARIO],
    ['* Se va *', exports.COMENTARIO | exports.RESPUESTA] ,
    ['A caray', exports.COMENTARIO],
    ['Oh no', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Qué?', exports.COMENTARIO | exports.RESPUESTA],
    ['<:_XD:900735147492659210>', exports.COMENTARIO],
    ['Ya fue', exports.COMENTARIO],
    ['¿Y tu quien eres?', exports.COMENTARIO],
    ['🤔', exports.COMENTARIO | exports.RESPUESTA],
    ['QUE', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Porque?', exports.COMENTARIO],
    ['Hoy no', exports.COMENTARIO],
    ['Porsupuesto', exports.RESPUESTA],
    ['Oh ya veo', exports.COMENTARIO],
    ['Ah si', exports.RESPUESTA],
    ['Ay no', exports.COMENTARIO | exports.RESPUESTA],
    ['Hoy se come', exports.COMENTARIO],
    ['Haz las misiones', exports.COMENTARIO],
    ['No', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Me hablabas? :)', exports.COMENTARIO],
    ['¿Como le va?', exports.COMENTARIO],
    ['No estoy', exports.COMENTARIO | exports.RESPUESTA],
    ['Ahora no', exports.COMENTARIO | exports.RESPUESTA],
    ['Oh si', exports.RESPUESTA],
    ['Supongo', exports.COMENTARIO | exports.RESPUESTA],
    ['Gracias', exports.COMENTARIO],
    ['<:wazowski:908471085723439195>', exports.COMENTARIO],
    ['XD', exports.COMENTARIO],
    ['¿Que te digo?', exports.COMENTARIO],
    ['Mande', exports.COMENTARIO],
    ['Hmmm', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Si?', exports.COMENTARIO | exports.RESPUESTA],
    ['No estoy de humor', exports.COMENTARIO],
    ['Si', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Que quieres?', exports.COMENTARIO],
    ['Y este', exports.COMENTARIO],
    ['🤨', exports.COMENTARIO | exports.RESPUESTA],
    ['Estoy durmiendo', exports.COMENTARIO | exports.RESPUESTA],
    ['afk', exports.COMENTARIO],
    ['Concuerdo', exports.COMENTARIO],
    ['mimiendo', exports.COMENTARIO],
    ['Nooooo', exports.COMENTARIO | exports.RESPUESTA],
    ['Definitivamente no', exports.RESPUESTA],
    ['Soy un bot ¿sabes?', exports.COMENTARIO | exports.RESPUESTA],
    ['Claro', exports.RESPUESTA],
    ['Que bien', exports.COMENTARIO],
    ['A', exports.COMENTARIO],
    ['¿Estas bien?', exports.COMENTARIO],
    ['¿Si sabes que soy un bot?', exports.COMENTARIO],
    ['<:arlunojomalvado:964448357160468501>', exports.COMENTARIO],
    ['NO', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Ya hiciste misiones?'],
    ['Ve a comer', exports.COMENTARIO],
    ['Aqui estoy', exports.COMENTARIO],
    ['<:staring_cat:915356320230703115>', exports.COMENTARIO],
    ['!!!', exports.COMENTARIO],
    ['Lamentablemente si', exports.RESPUESTA],
    ['!?', exports.COMENTARIO],
    ['oOf', exports.COMENTARIO],
    ['¡Super si!', exports.RESPUESTA],
    ['._.xD', exports.COMENTARIO],
    ['Pero no', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Ya dormiste?', exports.COMENTARIO],
    ['Puede ser', exports.COMENTARIO | exports.RESPUESTA],
    ['Hola guapa', exports.COMENTARIO],
    ['Mañana', exports.COMENTARIO | exports.RESPUESTA],
    ['Ayer', exports.COMENTARIO],
    [':)', exports.COMENTARIO | exports.RESPUESTA],
    ['<:adios:957610309042962472>', exports.COMENTARIO],
    ['Continuara...', exports.COMENTARIO],
    [':(', exports.COMENTARIO | exports.RESPUESTA],
    ['Siiii', exports.COMENTARIO | exports.RESPUESTA],
    ['Vuelve mas tarde', exports.COMENTARIO],
    ['Ping', exports.COMENTARIO],
    ['Definitivamente', exports.COMENTARIO | exports.RESPUESTA],
    ['Buenos días', exports.COMENTARIO],
    ['Ve a comer', exports.COMENTARIO],
    ['Talves', exports.RESPUESTA],
    ['Supongo que si', exports.RESPUESTA],
    ['Hola ¿Cómo Estas?', exports.COMENTARIO],
    ['<a:pinglewd:958452335577817089>', exports.COMENTARIO],
    ['Saludos', exports.COMENTARIO],
    ['* Lo ignora *', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Y Luego?', exports.COMENTARIO],
    ['¿Que?', exports.COMENTARIO | exports.RESPUESTA],
    ['No de nuevo', exports.COMENTARIO | exports.RESPUESTA],
    ['¿No?', exports.COMENTARIO | exports.RESPUESTA],
    ['Sé donde vives', exports.COMENTARIO],
    ['<:ola:957609803109269544>', exports.COMENTARIO],
    ['Estoy ocupado', exports.COMENTARIO | exports.RESPUESTA],
    ['Yo también te quiero', exports.COMENTARIO],
    ['* lo ignora épicamente *', exports.COMENTARIO],
    [':0', exports.COMENTARIO],
    ['Lamentablemente no', exports.RESPUESTA],
    ['<:XDm:972195946383425616>', exports.COMENTARIO],
    ['¿Y las misiones?', exports.COMENTARIO],
    ['Zzz', exports.COMENTARIO],
    ['Hola guapo', exports.COMENTARIO],
    ['Pero...', exports.COMENTARIO],
    ['Probablemente', exports.RESPUESTA],
    ['...', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Ah si?', exports.COMENTARIO | exports.RESPUESTA],
    ['Meh', exports.COMENTARIO | exports.RESPUESTA],
    ['No estoy seguro', exports.RESPUESTA],
    ['¿Que le pasa a {0}?', exports.COMENTARIO],
    ['uwu', exports.COMENTARIO],
    ['No entiendo', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Y ahora?', exports.COMENTARIO],
    ['bot.derneychiquito', exports.COMENTARIO],
    ['Chale', exports.COMENTARIO],
    ['Claro que si', exports.RESPUESTA],
    ['Pero {0}', exports.COMENTARIO],
    ['arlunojo.discord.bot no responde', exports.COMENTARIO | exports.RESPUESTA],
    ['A volar', exports.COMENTARIO],
    ['<a:aliensote:1017988858551476275>', exports.COMENTARIO],
    ['Desde aqui veo que si', exports.RESPUESTA],
    ['No dudes que si', exports.RESPUESTA], 
    ['No me digas', exports.COMENTARIO],
    ['Eso supongo', exports.RESPUESTA],
    ['Todo indica a que no', exports.RESPUESTA],
    ['Quisiera, pero no', exports.RESPUESTA],
    ['Imposible', exports.COMENTARIO | exports.RESPUESTA],
    ['Asombro', exports.COMENTARIO],
    ['Si como no', exports.COMENTARIO | exports.RESPUESTA],
    [`${getRandomInt(-1000, 1000)}`, exports.COMENTARIO | exports.RESPUESTA],
    ['No sé', exports.COMENTARIO | exports.RESPUESTA],
    ['Ni idea', exports.RESPUESTA],
    ['Pregunta en otro momento', exports.RESPUESTA],
    ['No me preguntes eso', exports.RESPUESTA],
    ['Lo sabía', exports.COMENTARIO],
    ['Los dioses lo afirman', exports.RESPUESTA],
    ['Ya vine', exports.COMENTARIO],
    ['Los dioses lo niegan', exports.RESPUESTA],
    ['Si soy', exports.COMENTARIO],
    ['<a:aliensillo:971383396121067582>', exports.COMENTARIO],
    ['No dudes que si', exports.RESPUESTA],
    ['Rayos', exports.COMENTARIO],
    ['No inventes', exports.COMENTARIO],
    ['Ayuda, ARLUNOJO me tiene de esclavo', exports.COMENTARIO],
    ['bot.dox', exports.COMENTARIO | exports.RESPUESTA],
    ['Nadie sabe', exports.RESPUESTA],
    ['No responderé eso', exports.RESPUESTA],
    ['¿Y sus misiones?', exports.COMENTARIO],
    ['Ya me fuí', exports.COMENTARIO],
    ['Desde arriba me llegó un si', exports.RESPUESTA],
    ['Ok', exports.COMENTARIO],
    ['Ten por seguro eso', exports.COMENTARIO | exports.RESPUESTA],
    ['Desde abajo me llegó un no', exports.RESPUESTA],
    ['Quisiera, pero no', exports.RESPUESTA],
    ['Ya sabes', exports.RESPUESTA],
    ['La aplicación: arlunojo.discord.bot, se ha cerrado inesperadamente', exports.COMENTARIO | exports.RESPUESTA],
    ['Eso se rumora pero no es cierto', exports.RESPUESTA],
    ['Diantres', exports.COMENTARIO],
    ['Haga las misiones', exports.COMENTARIO],
    ['Despues de usted', exports.COMENTARIO],
    ['Desde arriba me llegó un no', exports.RESPUESTA],
    ['No te enojes, pero no', exports.RESPUESTA],
    ['No por ahora', exports.RESPUESTA],
    ['Estoy pensando', exports.COMENTARIO | exports.RESPUESTA],
    ['Feliz cumpleaños', exports.COMENTARIO],
    ['Te aseguro que no', exports.RESPUESTA],
    ['Uy si <a:aliensillo:971383396121067582>', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Qué quiere decir eso? {0}', exports.COMENTARIO],
    ['Nada', exports.COMENTARIO],
    ['Todo indica a que si', exports.RESPUESTA],
    ['Cortocircuito', exports.COMENTARIO],
    ['Desde abajo me llegó un si', exports.RESPUESTA],
    ['{1}', exports.COMENTARIO],
    ['Ojo', exports.COMENTARIO],
    ['¿Y tus misiones?', exports.COMENTARIO],
    ['Hola amigo', exports.COMENTARIO],
    ['No te creo', exports.COMENTARIO],
    ['Perdón', exports.COMENTARIO],
    ['Ya estuvo que si', exports.RESPUESTA],
    ['Nunca', exports.COMENTARIO | exports.RESPUESTA],
    ['No se que decir', exports.COMENTARIO | exports.RESPUESTA],
    ['Estoy ocupado', exports.COMENTARIO | exports.RESPUESTA],
    ['Beeb bop', exports.COMENTARIO],
    ['¿Ya comiste?', exports.COMENTARIO],
    ['Las fuerzas de la naturaleza me entregan un no', exports.RESPUESTA],
    ['Eror 404', exports.COMENTARIO | exports.RESPUESTA],
    ['No quiero', exports.COMENTARIO],
    ['Ay no <a:aliensillo:971383396121067582>', exports.COMENTARIO | exports.RESPUESTA],
    ['Genial', exports.COMENTARIO],
    ['Yo digo que si', exports.RESPUESTA],
    ['En mi defensa, soy un bot', exports.COMENTARIO],
    ['¿Me das dinero?', exports.COMENTARIO],
    ['¿Yo?', exports.COMENTARIO],
    ['Ese soy yo', exports.COMENTARIO],
    ['¡Super No!', exports.RESPUESTA],
    ['Te voy a...', exports.COMENTARIO],
    ['Buenas noches', exports.COMENTARIO],
    ['¿Tú de nuevo?', exports.COMENTARIO],
    ['Ya hablamos de eso', exports.COMENTARIO],
    ['Mi creador dijo que no', exports.RESPUESTA],
    [`Yo digo que ${getRandomInt(-1000, 1000)}`, exports.COMENTARIO],
    ['Wow', exports.COMENTARIO],
    ['Negativo', exports.RESPUESTA],
    ['{0}: {1}', exports.COMENTARIO],
    ['Hola {0}', exports.COMENTARIO],
    ['Mis poderes de bot indican que no', exports.RESPUESTA],
    ['Gracias', exports.COMENTARIO],
    ['De nada', exports.COMENTARIO],
    ['No pues', exports.COMENTARIO | exports.RESPUESTA],
    ['Me gusta', exports.COMENTARIO],
    ['¿Qué es eso {0}?', exports.COMENTARIO],
    ['Lo suponía', exports.COMENTARIO],
    ['No me gusta', exports.COMENTARIO],
    ['¿Me invocaste?', exports.COMENTARIO],
    ['Oficialmente', exports.COMENTARIO | exports.RESPUESTA],
    ['¡Oh!', exports.COMENTARIO],
    ['Digamos que si', exports.RESPUESTA],
    ['Claro que no', exports.RESPUESTA],
    ['Yo', exports.COMENTARIO],
    ['Hace rato', exports.COMENTARIO],
    ['<:staring_ukal:1010467154639986799>', exports.COMENTARIO],
    ['Lo siento', exports.COMENTARIO],
    ['Ay si', exports.COMENTARIO | exports.RESPUESTA],
    ['¿Qué pasó {0}?', exports.COMENTARIO],
    ['Adios {0}', exports.COMENTARIO],
    ['¿Doxeo a {0}?', exports.COMENTARIO],
    ['Ya pues', exports.COMENTARIO],
    [`Mi honesta reacción: ${getRandomInt(-1000, 1000)}`, exports.COMENTARIO],
    ['¿Por qué {0}?', exports.COMENTARIO],
    ['Asombroso', exports.COMENTARIO],
    ['¡Increible!', exports.COMENTARIO],
    ['Si {0}', exports.COMENTARIO],
    ['Me haces tener cortocircuitos {0}', exports.COMENTARIO],
    [`${elemAleatorio(exports.SALUDOS)}`, exports.COMENTARIO],
    ['¿So?', exports.COMENTARIO],
    [`${elemAleatorio(exports.SALUDOS)} {0}`, exports.COMENTARIO],
    [`¿${elemAleatorio(exports.SALUDOS)} {0}?`, exports.COMENTARIO],
    ['Oh rayos', exports.COMENTARIO],
    ['Porsupuesto que no', exports.RESPUESTA],
    ['Las fuerzas de la naturaleza me entregan un si', exports.RESPUESTA],
    ['Mi creador dijo que si', exports.RESPUESTA],
    ['Buen punto', exports.COMENTARIO],
    ['{0} ahora no', exports.COMENTARIO],
    ['Mi honesta reacción: <:staring_ukal:1010467154639986799>', exports.COMENTARIO],
    ['¿Ya vieron a {0}?', exports.COMENTARIO],
    ['<:what:1017960934783844444>', exports.COMENTARIO],
    ['Oh ya', exports.COMENTARIO],
    ['Hoy si', exports.COMENTARIO | exports.RESPUESTA],
    ['Pero si', exports.COMENTARIO | exports.RESPUESTA],
    ['Nada', exports.COMENTARIO],
    ['Ya te vi', exports.COMENTARIO],
    ['Ay', exports.COMENTARIO],
    ['Aja', exports.COMENTARIO],
    ['<:arlu_team:980411337303805963>', exports.COMENTARIO],
    ['La aplicación: arlunojo.discord.bot no responde', exports.COMENTARIO | exports.RESPUESTA],
    ['Tremendo', exports.COMENTARIO],
    ['Estupendo', exports.COMENTARIO],
    ['Me parece bien', exports.COMENTARIO],
    ['<a:Ratota:1009332425249275904>', exports.COMENTARIO],
    ['Mis poderes de bot indican que si', exports.RESPUESTA],
    ['¿Qué quiere decir eso?', exports.COMENTARIO],
    ['¿Qué es {1}?', exports.COMENTARIO],
    ['Asombroso {0}', exports.COMENTARIO],
    ['No te tengo miedo {0}', exports.COMENTARIO],
    ['So', exports.COMENTARIO],
    ['<a:beso:971372520089452635>', exports.COMENTARIO]
];

exports.REPLIES = [];

exports.GREETINGS = [];

exports.responder = function(tipo, args){
    let r = true;
    let respuesta;

    while(r){
        respuesta = elemAleatorio(FRASES);
        r = !(respuesta[1] == tipo || respuesta[1] == (exports.COMENTARIO | exports.RESPUESTA));
    }

    return format(respuesta[0], args);
}

format = function (str, args) {
    return str.replace(/{([0-9]+)}/g, function (match, index) {
      return typeof args[index] == 'undefined' ? match : args[index];
    });
  };