const { MessageEmbed } = require('discord.js');
const { elemAleatorio, getRandomInt } = require('../../arlutils');

module.exports = {
    name: 'ganar',
    description: '¿Ganar o no ganar?',
    hide: false,
    execute: exec
};

let usr = {tag: 'undefined'};

MSGS = [
    'Y... \n ¡Felicidades has ganado!',
    'Perdiste',
    '¡YAY! ¡Ganaste',
    'Casi ganas pero no ganaste :(',
    'No no no, ya ganaste',
    'Y... \n ¡Felicidades has perdido!',
    'Tenemos un ganador',
    'Ups, perdiste',
    '¡Pero mira como ganaste!',
    'Uy creo que no ganaste',
    '¡WOW! ¡Miren a nuestro ganador!',
    'No, hoy te toca perder',
    'Jajaja ganaste',
    'Jajaja perdiste',
    'Mi creador quizo que si ganes',
    'No se pudo encontrar la palabra: Ganaste',
    'Casi pierdes, pero ganaste :)',
    'No no no, ya perdiste',
    '{0} ya ganó',
    'Ay no, perdiste',
    'Lamento informarte que ¡Has Ganado!',
    '¡Pero mira como perdiste!',
    'Hoy ganaste, mañana quien sabe',
    'Debes tener mala suerte que has perdido',
    '¡Ay caramba ganaste!',
    'Lamentamos informarte que\n¡Has perdido!',
    'Ay no, ganaste',
    'Que mala suerte, perdiste',
    'Ganaste',
    '{0} ya perdió',
    'Ups, ganaste',
    '¡WOW! ¡Miren a nuestro perdedor!',
    'Ay si, ganaste',
    'Lo siento, perdiste :\'v',
    'Si, hoy te toca ganar',
    'Hoy perdiste, mañana quien sabe',
    'Que buena suerte, ganaste',
    'Olvidé que es ganar\nasí que perdiste',
    '¡Felicitaciones a nuestro ganador!',
    'Imposible, perdiste',
    'Olvidé que es perder\nasí que ganaste',
    'Perdiste épicamente',
    'Imposible, ganaste',
    'Todos querían que ganaras\nPero perdiste',
    'Hay un 50% de probabilidad de ganar o no ganar\nY te tocó ganar',
    '¡Felicitaciones a nuestro perdedor!',
    'Ganaste épicamente',
    'Hay un 50% de probabilidad de ganar o no ganar\nY te tocó no ganar',
    'Todos querían que perdieras\nPero ganaste',
    'Me salió una mosca en la sopa\nAsí que perdiste',
    'Desde que el primer átomo existió, tu destino era ganar ahora',
    'Adios, no ganaste',
    'Hoy eres mi favorito así que ganaste',
    'En el interior sabías que perdiste',
    'Mi peluche cayó de pie, por lo tanto ¡Ganaste!',
    'Me siento mal\nPerdiste',
    'Según mis cálculos, ¡Ganaste!',
    'Aveces se gana y aveces no\nAhora no ganaste',
    'Para ganar debes perder\nGanaste',
    'Perdiste por que se me dió la gana',
    'Hola, si ganaste',
    'Hoy no eres mi favorito, así que no ganaste',
    'En el interior sabías que ganaste',
    'No estoy capacitado para ganar\nAsí que perdiste',
    'Presionaste muy bien enviar\n¡Ganaste!',
    'Debo admitir que quería que ganaras\nPero, no ganaste',
    'No me lo esperaba\nGanaste',
    'Mi peluche cayó de cabeza, por lo tanto ¡Perdiste!',
    'Le pregunté a un arbol y me dijo:\n¡Ganaste!',
    'Te ves muy sospechoso\nNo ganaste',
    'Me siento bien\nGanaste',
    'Según mis cálculos, ¡No ganaste!',
    'Ganaste por que se me dió la gana',
    'Ya ganaste mucho, por eso perdiste',
    'No estoy capacitado para perder\nAsí que ganaste',
    'Presionaste muy mal enviar\nPerdiste',
    'Debo admitir que quería que perdieras\nPero ganaste',
    'Le pregunté a un arbol y me dijo:\n¡Perdiste!',
    'Te ves muy bien\nGanaste',
    'Desde que el primer átomo existió, tu destino era perder ahora',
    '¿Creíste que ganarias?\n¡Pues si ganaste!',
    'Mi creador no quizo que ganes',
    'Me gusta estar contigo\n Ganaste',
    'Un señor me vió feo\nPerdiste',
    'Ya perdiste mucho, por eso ganaste',
    'No sé si lo escribí bien\n||Perdiste||',
    'Debido a tu honestidad, ganaste',
    '¿Creíste que ganarias?\n¡Pues no ganaste!',
    'El misterio aqui es: ¿Cómo ganaste?',
    'No me gusta estar contigo\nPerdiste',
    'Una persona misteriosa me pasó un papel y dice:\n¡Ganaste!',
    'Vi escrito en una ventana que perdiste',
    'No sé si lo escribi bien\n||Ganaste||',
    'Debido a que hiciste trampa, perdiste',
    'Te has esforzado mucho, ganaste',
    'El misterio aqui es: ¿Cómo perdiste?',
    'Vi escrito en una ventana que ganaste',
    'Una persona misteriosa me pasó un papel y dice:\n¡Perdiste!',
    'Aveces se gana y aveces no\nAhora ganaste',
    'No te esforzaste lo suficiente, perdiste',
    'Un perro aprendió a hablar y dice que ganaste',
    'Para ganar debes perder\nPerdiste',
    'Vi a un niño caminar por primera vez, por lo tanto, ganaste',
    'Vi a un niño caerse, por lo tanto, perdiste',
    'Aqui estoy\nganaste',
    'No estoy\nperdiste',
    'Me das miedo, ganaste',
    'No te tengo miedo, perdiste',
    'Según un reporte médico, ganaste',
    'Según un reporte médico, perdiste',
    'La inflación esta a la alza pero te preparaste\nPor eso, ganaste',
    'La inflación esta a la alza\nPor eso, perdiste',
    'Tu amor por los animales te hizo ganar',
    'Tu amor por los animales te hizo perder',
    'No se pudo encontra la palabra: Perdiste',
    'Dice en un letrero que:\n¡Perdiste!',
    'Dice en un letrero que:\n¡Ganaste!',
    'No comiste bien\nPerdiste',
    'Comiste bien\nGanaste',
    'Mi creador dice que perdiste',
    'Mi creador dice que ganaste',
    'Me dieron un café con la palabra:\n¡Perdiste!',
    'Me dieron un café con la palabra:\n¡Ganaste!',
    'Según los testimonios, el individuo estaba en su casa cuando el presunto delincuente rompió la ventana, entró y con un arma de fuego le apuntó a la cara diciendo las siguientes palabras:\n¡Perdiste!',
    'Según los testimonios, el individuo estaba en su casa cuando el presunto delincuente rompió la ventana, entró y con un arma de fuego le apuntó a la cara diciendo las siguientes palabras:\n¡Ganaste!',
    'Hoy tienes una pésima vibra, perdiste',
    'Hoy tienes una gran vibra, ganaste',
    'Mi juguete de max steel afirma que perdiste',
    'Mi juguete de max steel afirma que ganaste',
    'Me hicieron daño los tacos, perdiste',
    'Que delicia, ganaste',
    'No me ajustó la despensa, perdiste',
    'Compré muchas cosas, en una dice: ¡Ganaste!',
    'wqFQZXJkaXN0ZSE=',
    'wqFHYW5hc3RlIQ==',
    '<:momichisad:972195531306704966>',
    '<a:aliensote:1017988858551476275>',
    'Las especies evolucionan para ganar, pero no fue tu caso\nPerdiste',
    'Las especies evolucionan para ganar, y tu lo haz hecho\nGanaste',
    'Dejaste la luz prendida, perdiste',
    'Si apagaste la luz, ganaste',
    'No pagaste impuestos\nPerdiste',
    'Pagaste bien los impuestos\nGanaste',
    'Se te olvido pagar el internet, perdiste',
    'Recordaste pagar el internet, ganaste',
    'Hoy es un buen día para perder\nPerdiste',
    'Hoy es un buen día para ganar\nGanaste',
    '¡Mira el cielo!\n¡Las nubes formaron la palabra \"Perdiste\"!',
    '¡Mira el cielo!\n¡Las nubes formaron la palabra \"Ganaste\"!',
    'No sé quien eres\nPero Perdiste',
    'No sé quien eres\nPero ganaste'
];

function exec(msg, args, cliente, discord){
    let i = getRandomInt(0, MSGS.length);
    let gana = (i % 2 == 0);
    usr.tag = msg.author.name;
    var embed = new MessageEmbed();
    embed.setTitle("Bienvenidos a ganar o no ganar");
    embed.setDescription(MSGS[i] + '\n\n');
    if(gana){
        embed.setColor('#5df542');
    }else{
        embed.setColor('#f54242');
    }
    msg.reply({embeds: [embed]});
    return true;
}